---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/Setup
  label: Setup
  create: all
  match: "**/*"
- type: directory
  path: content/Shortcuts
  label: Shortcuts
  create: all
  match: "**/*"
- type: directory
  path: content/module1
  label: Module1
  create: all
  match: "**/*"
- type: directory
  path: content/module2
  label: Module2
  create: all
  match: "**/*"
- type: directory
  path: content/module3
  label: Module3
  create: all
  match: "**/*"
upload_dir: static/upload
public_path: "/web-cheatsheet/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
version: 0.54.0
