---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
  description: añadir titulo
- type: datetime
  name: date
  label: date
  description: date
  config:
    date_format: DD/MM/YYYY
- type: number
  label: weight
  name: weight
  description: order
